spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=Asia/Seoul
    username: root
    password: root
  mail:
    host: smtp.naver.com # smtp ?? ??
    port: 465
    username: ${userName}
    password: ${passWord}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true

  data:
    redis:
      port: 6379
      host: 127.0.0.1

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
  #    database-platform: org.hibernate.dialect.MySQL8Dialect
  #        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.orm.jdbc.bind: trace # SpringBoot 3.x, hibernate6
